// LOGIN ACTION TYPES

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_ERROR = "LOGIN_ERROR";

//GET ALL USERS

export const GET_AUTH_TOKEN_START = "GET_AUTH_TOKEN_START";
export const GET_AUTH_TOKEN_FAILURE = "GET_AUTH_TOKEN_FAILURE";
export const GET_AUTH_TOKEN_SUCCESS = "GET_AUTH_TOKEN_SUCCESS";
export const GET_AUTH_TOKEN_ERROR = "GET_AUTH_TOKEN_ERROR";


//SEND MEETING INVITE ACTION TYPES

export const GET_AN_ALBUM_START = "GET_AN_ALBUM_START";
export const GET_AN_ALBUM_FAILURE = "GET_AN_ALBUM_FAILURE";
export const GET_AN_ALBUM_SUCCESS = "GET_AN_ALBUM_SUCCESS";
export const GET_AN_ALBUM_ERROR = "GET_AN_ALBUM_ERROR";


//GET CARD DECK ACTION TYPES

export const SEARCH_START = "SEARCH_START";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_ERROR = "SEARCH_ERROR";


// //GET CARD DECK ACTION TYPES

// export const SEARCH_START = "SEARCH_START";
// export const SEARCH_FAILURE = "SEARCH_FAILURE";
// export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
// export const SEARCH_ERROR = "SEARCH_ERROR";
